<a href="https://colab.research.google.com/github/Jahnavitalluri01/Big-Data/blob/main/ICP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.random.randint(1, 21, size=15)

arr = arr.reshape(3, 5)

print("Shape of array:", arr.shape)

print("Original array:\n", arr)

for i in range(arr.shape[0]):
    maxx = arr[i].argmax()
    arr[i][maxx] = 0

print("Modified array:\n", arr)


Shape of array: (3, 5)
Original array:
 [[ 8 19 14  1 18]
 [ 5  6 10  6  9]
 [12  2  9 16  7]]
Modified array:
 [[ 8  0 14  1 18]
 [ 5  6  0  6  9]
 [12  2  9  0  7]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Type:", type(arr))
print("Data type:", arr.dtype)


Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int64


In [ ]:
import numpy as np

arr1 = np.array([[3, -2],
              [1,  0]])

eigenvalues, eigenvectors = np.linalg.eig(arr1)

print("Eigenvalues:")
print(eigenvalues)
print("\nRight eigenvectors:")
print(eigenvectors)


Eigenvalues:
[2. 1.]

Right eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [ ]:
import numpy as np

arr = np.array([[0, 1, 2],
                [3, 4, 5]])

sum = np.trace(arr)

print("Sum of diagonal elements:", sum)

Sum of diagonal elements: 4


In [ ]:
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])

reshaped_arr = arr.reshape(2, 3)

print("Original array:")
print(arr)

print("\nReshaped array:")
print(reshaped_arr)

Original array:
[[1 2]
 [3 4]
 [5 6]]

Reshaped array:
[[1 2 3]
 [4 5 6]]


In [ ]:
https://drive.google.com/file/d/1m59nK3t-fMAMiXlw30mkOoQ5JpQnrlgO/view?usp=sharing